#stage-1: build React
FROM	node:18-alpine as builder
WORKDIR	/app
COPY	package*.json .
RUN		npm install
COPY	. .
RUN npm run build

#stage-2: Prepare Nginx
FROM nginx
#EXPOSE 80
COPY --from=builder /app/build /usr/share/nginx/html


